name: PR Automática com gh CLI

on:
  push:
    branches:
      - "feature/**"

jobs:
  criar-pr:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🛠️ Verifica se o GitHub CLI está instalado
        run: |
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI não encontrado. Instalando..."
            sudo apt update && sudo apt install gh -y
          else
            echo "GitHub CLI já está instalado."
          fi

      - name: ✨ Cria Pull Request automaticamente
        run: |
          gh pr create \
            --title "✨ PR automática: ${{ github.ref_name }}" \
            --body "Essa PR foi gerada automaticamente após push na branch `${{ github.ref_name }}`." \
            --base main \
            --head ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
