name: PR Automática com GitHub CLI 💜

on:
  push:
    branches:
      - "feature/**"

jobs:
  criar-pr:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🧪 Verifica se gh CLI está disponível
        run: |
          if ! command -v gh &> /dev/null; then
            echo "🔧 Instalando GitHub CLI..."
            sudo apt update && sudo apt install gh -y
          else
            echo "✅ GitHub CLI já está disponível."
          fi

      - name: ✨ Cria Pull Request automaticamente
        run: |
          echo "🔍 Branch atual: ${{ github.ref_name }}"
          echo "📬 Criando PR da branch '${{ github.ref_name }}' para 'main'..."

          gh pr list --head "$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')" --json number

          gh pr create \
            --title "✨ PR automática: ${{ github.ref_name }}" \
            --body "Essa Pull Request foi gerada automaticamente após push na branch `${{ github.ref_name }}`." \
            --base main \
            --head "$(echo '${{ github.ref }}' | sed 's/refs\/heads\///')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
